### ISSUE TITLE
Remember LED sign colors

### ISSUE THREAD

**Issue by jerrylee17** [jerrylee17/printingRPC#14]
Health check needs to pass LED sign current color

**Comment by hsorathia** [comment]
me do

**Comment by evanugarte** [comment]
### 3/2 Meeting
1. Add a function to the [`LedSignServicer` class](https://github.com/jerrylee17/printingRPC/blob/c637ac5b54996d68d1100dbab1735e3aa0b9aceb/server/ledsign/led_sign_server.py#L13) that saves the fields sent from the website.
2. Add fields to the [`HealthCheckResponse`](https://github.com/jerrylee17/printingRPC/blob/c637ac5b54996d68d1100dbab1735e3aa0b9aceb/proto/led_sign.proto#L13) proto.
